# Generated by Django 4.0.4 on 2022-05-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_jogo', models.CharField(max_length=30)),
                ('tipo_de_jogo', models.CharField(max_length=30)),
                ('preço_do_jogo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descrição_do_jogo', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
            options={
                'verbose_name_plural': 'Jogos',
                'ordering': ['nome_do_jogo'],
            },
        ),
    ]
