# Generated by Django 4.0.4 on 2022-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_games_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Usuários'},
        ),
    ]
