# Generated by Django 4.0.4 on 2022-05-24 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jogos', '0004_alter_games_options_games_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='games',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
