# Generated by Django 4.0.4 on 2022-05-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0006_alter_games_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='user',
        ),
    ]
